name: Deploy Power Platform Solution

on:
  push:
    branches:
      - main  # Trigger deployment to production on the main branch
      - dev   # Trigger deployment to testing on the dev branch

  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - development
          - testing
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [development, testing, production]

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Power Platform CLI
        run: npm install -g pac-cli

      - name: Authenticate with Power Platform
        run: pac auth create --url ${{ secrets.ENV_URL }} --tenant ${{ secrets.TENANT_ID }} --client-id ${{ secrets.CLIENT_ID }} --client-secret ${{ secrets.CLIENT_SECRET }}

       
      - name: Export Solution from Development
        if: matrix.environment == 'development'
        run: |
          pac solution export --path ./.github/workflows/ --name CustomerandProducts --target managed --overwrite
          
      - name: Import Solution to Testing
        if: matrix.environment == 'testing'
        run: |
         pac solution import --path ./.github/workflows/CustomerandProducts.zip --overwrite-same-version --activate-plugins

      - name: Import Solution to Production
        if: matrix.environment == 'production'
        run: |
          pac solution import \
            --path exported_solution.zip \
            --async

      - name: Verify Import
        run: |
          pac solution list
